spring:
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      password: your_redis_password  # Add this if your Redis server requires a password
      timeout: 60000  # Connection timeout in milliseconds
      lettuce:
        pool:
          max-active: 8  # Maximum number of connections
          max-idle: 8  # Maximum number of idle connections
          min-idle: 0  # Minimum number of idle connections


server:
  port: 8282

logging:
  level:
    org:
      springframework:
        security: DEBUG

kakao:
  api:
    key: ${KAKAO.API.KEY}
  redirect:
    url: ${KAKAO.REDIRECT.URL}

tourInfo:
  base_url: ${TOURINFO.URL}
  service_key: ${TOURINFO.KEY}
  data_format: ${TOURINFO.FORMAT}


springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**

movies:
  api:
    key: ${TMDB.API.KEY}


jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-period: 1296000  # Access token 만료 기간 (15일 = 1296000초)
  refresh-token-expire-period: 1296000  # Refresh token 만료 기간 (15일 = 1296000초)