name: Build and Deploy to NCP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    name: build image

    steps:
      - name: get repository from github
        uses: actions/checkout@v3

      - name: setup jdk17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: setup gradle
        run: chmod +x gradlew

      - name: build gradle
        run: ./gradlew clean build -x test

      - name: docker build and push
        run: |
          docker login ${{ secrets.DOCKER_REPO }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/booyoungee-server:develop .
          docker push ${{ secrets.DOCKER_REPO }}/booyoungee-server:develop

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name : NCP login and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            sudo docker compose -f /root/docker-compose.yml pull
            sudo docker compose -f /root/docker-compose.yml up -d