name: CI/CD Pipeline

on:
  push:
    branches: [ "TC-45" ]
  pull_request:
    branches: [ "TC-45" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Load environment variables from .env file
        run: |
          set -a
          source .env
          set +a

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -f Dockerfile.Backend ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

      - name: Deploy to production (optional)
        run: |
          docker run -d -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
